### ISSUE TITLE
Doubts when installing plugin.

### ISSUE THREAD

**Issue by danielweil** [redmine-git-hosting/redmine_git_hosting#756]
Hello Guys, 

Can you please help me?
I don't know if it possible to use this plugin in my local machine. I wanted to test it before going for the actual server where Redmine is going to be running.

I am trying to follow the instalation guide. I go through all steps until I have to test a ssh connection to my gitolite repository. I do not understand if Redmine have to be running or not, but when I try to do the ssh, it gives an error saying the connection refused on port 22.

I want to be able to test the plugin because it seems very usefull, but I have been all day long and could not go though.

If anyone can help me, I would be gratefull.

**Comment by PowerKiKi** [comment]
See https://github.com/redmine-git-hosting/redmine_git_hosting/issues/795
