### ISSUE TITLE
Question - nginx gitolite http auth handler for redmine

### ISSUE THREAD

**Issue by dev-trilobyte** [redmine-git-hosting/redmine_git_hosting#762]
Hello,

i newly set up a redmine with redmine_git_hosting plugin and gitolite. Our old version was using Apache as HTTP server and there existed an AuthHandler to authenticate HTTP requests against the redmine user database.
As i have not found something similiar for Nginx i wrote a little perl cgi script for this case.

Question: is there any interest for a contribution to this plugin for other people to use? Its not intended for high traffic sites but probably helps some people to set up auth for gitolite in combination with redmine...

Thanks,
Stefan Seide

**Comment by PowerKiKi** [comment]
Assuming this is obsolete

**Comment by dev-trilobyte** [comment]
Nice to hear its not needed anymore. But i miss probably something about the new equivalent to the Addon- Installation described here http://redmine-git-hosting.io/how-to/install-addons/ with Nginx instead of Apache.

Can you point me to the documentation to use your "new" way?
Thanks

**Comment by PowerKiKi** [comment]
I haven't been very clear. What I meant that I assume that the original issue is solved, or is too old be relevant.

I don't have any solution to suggest on how to integrate Gitolite and nginx.

**Comment by dev-trilobyte** [comment]
Ok - so i was not clear here too it seems.
Are you interested in an Nginx configuration and Authentication helper script similar to the Apache one mentioned above? Than i can provide our config/script. Or are there no people using Redmine together with NGinx, threfore no need for it?

**Comment by PowerKiKi** [comment]
IMHO I am not sure it is necessary. Redmine already gives a browser version of git, and I personally prefer ssh protocol for git itself.

But feel free to post it somewhere, in a blog, or even in this issue, to keep it as a form of archive. Just in case somebody stumble upon it...
