### ISSUE TITLE
[Feature request] Make a "quick" way to get a demo site working (i.e. docker image)

### ISSUE THREAD

**Issue by toastedcrumpets** [redmine-git-hosting/redmine_git_hosting#795]
This is an amazing piece of software, and I think the best way to get that across is to let new users try a demo of it, but unfortunately there's quite a high entry bar to new users due to challenges around setting up gitolite and the plugin, let alone if they don't have a working redmine install. 

To help with that, I made a docker-compose setup that boots redmine with git_hosting installed here:
https://github.com/toastedcrumpets/redmine-git-docker-example

New users can just clone the repo, then type
`docker-compose up`
And they'll have a new redmine instance with git_hosting on http://localhost:8080. Gitolite even appears on localhost:2222 and everything is set up (except hooks, I didn't figure out how to do that automatically yet). 

I also note that if you want to get redmine_git_hosting working inside Kubernetes this is a nice path forward.

I would suggest that the install instructions offer this as an option and suggest it for kubernetes, provided you like the implementation?

**Comment by toastedcrumpets** [comment]
I also note that this image helped another user resolve their issues around installation:
#777 #790 
Maybe the biggest value of this exercise is in having a set of instructions/script that actually fully sets up everything?

**Comment by PowerKiKi** [comment]
There is indeed value in having a way to set up an entire environnement automatically. So thanks for sharing it.

However, as you might I have guessed by now, we barely have the bandwidth to maintain the project as is. So I don't think we should increase its scope by introducing a docker image. But feel free to keep you project alive and talk about it around here.
