### ISSUE TITLE
Ruby 3.1 support (redmine 5.0.x)

### ISSUE THREAD

**Issue by tomhub** [redmine-git-hosting/redmine_git_hosting#803]
Hi

Is plugin going to be updated for redmine 5.0 with ruby 3.0 and 3.1 ?

**Comment by picman** [comment]
+1

**Comment by Alwaysin** [comment]
We're interested as well!

**Comment by PowerKiKi** [comment]
See https://github.com/redmine-git-hosting/redmine_git_hosting/releases/tag/6.0.0
