### ISSUE TITLE
New GitHub organization

### ISSUE THREAD

**Issue by PowerKiKi** [redmine-git-hosting/redmine_git_hosting#819]
@n-rodriguez, I would like to create a new GitHub organization to host all projects related to redmine_git_hosting. Because right now it's a bit of a mess to maintain with dependencies scarreted left and right and quite a few of them looks only half maintained.

My hope is that with a proper organization, to which I would add at least yourself and @alexandermeindl, we can better keep everything maintained together.

So my question is, if I create said organization, would you be willing to transfer the ownership of the following repo ?

- https://github.com/jbox-web/gitolite-rugged
- https://github.com/jbox-web/grack
- https://github.com/jbox-web/redmine_git_hosting

PS: Additionally, I would also include https://github.com/ogom/redmine_sidekiq in that org.

**Comment by n-rodriguez** [comment]
Why not :) how would you name it?

**Comment by PowerKiKi** [comment]
I created https://github.com/redmine-git-hosting and invited both of you as owners. And I threw in a logo made in 5 seconds.

I'd appreciate if you could transfer ownership of the 3 others projects.

**Comment by n-rodriguez** [comment]
Done! I also transfered https://github.com/jbox-web/gitolite which is the previous version of https://github.com/jbox-web/gitolite-rugged

**Comment by PowerKiKi** [comment]
Thank you !
